### ISSUE TITLE
IntelliJ 2021.3 Support

### ISSUE THREAD

**Issue by mai93** [bazelbuild/intellij#3001]
The IntelliJ 2021.3 EAP was [released](https://www.jetbrains.com/idea/nextversion/#section=windows) a few weeks ago and we have made the necessary changes to enable working towards supporting this new version. You can now build the Bazel plugin for the EAP using: `intellij-oss-under-dev` or `intellij-ue-oss-under-dev` product-version aliases for CE and UE respectively.  For compatibility fixes, we encourage you to follow the [contributions guidelines](https://github.com/bazelbuild/intellij#contributions) described in the plugin documentation.

Now, we are looking for a volunteer from the community to organize the community work and contributions towards 2021.3 support. The volunteer should identify the breaking changes and drive the community work to fix them. Don't worry if you don't know how to do this. We can give you pointers if necessary. 

Please nominate yourself before the community meeting on October 28, 2021 at 8am Pacific Time. To do so, send us a quick note with your name and contact details to product@bazel.build. Also, please show up at the community meeting on Oct 28th.

**Comment by mai93** [comment]
Please note that the Bazel plugin can now be built successfully for IntelliJ 2021.3. However, some plugin tests are failing for this version [[failing tests logs](https://buildkite.com/bazel/intellij-plugin/builds/14171#581812c8-56cf-45eb-a31e-6fac334cd710)].

We are still looking forward to your contributions to fix these tests so that we can be able to release a plugin version compatible with IntelliJ 2021.3 EAP.

**Comment by maomaobug** [comment]
When will the fix be released?  IntelliJ 2021.3 was released out but the plugin's broken.

**Comment by philwo** [comment]
Hi @maomaobug and others,

We're on it! We were on a pretty good track after @jwillebrands kindly contributed the required fixes for the failing tests in the Community Edition (https://github.com/bazelbuild/intellij/pull/3074), but unfortunately between the last EAP and the final 2021.3 release (https://github.com/bazelbuild/intellij/pull/3095), there were again some incompatible changes in the plug-in API that we couldn't prepare for, so more stuff broke. :(

Here's where you can track the current progress (click the latest job that ran on the `master` branch and check for the soft-failing "IntelliJ Under Development" jobs):
- https://buildkite.com/bazel/intellij-plugin
- https://buildkite.com/bazel/intellij-ue-plugin

We have one engineer on the team who recently joined working on the compatibility fixes for IntelliJ 2021.3, so we're positive that we'll get there. Help from the community with fixing broken tests is really appreciated - if anyone wants to send a PR that gets us closer to a green CI build, we'd really appreciate it and merge it quickly. Please add a comment here referencing it to ensure it gets looked at quickly.

As soon as the tests pass, we can release a beta version of the plug-in that should work with IntelliJ 2021.3. Please feel free to ping this issue if you would like an update again in the future.

Cheers,
Philipp

**Comment by seanabraham** [comment]
👋 @philwo —

Are there any updates on tests or when we might see the beta version of the plugin which supports IntelliJ 2021.3 released?

Thanks!

**Comment by jasonmartens** [comment]
Hey all you JetBrains paid users, it would be helpful if you file bugs about this so JetBrains will stop breaking plugins every release.

**Comment by fkorotkov** [comment]
Fixed tests in #3155. @philwo PTAL

**Comment by philwo** [comment]
@fkorotkov Thank you! I'll check it out immediately.

**Comment by alice-ks** [comment]
@fkorotkov Thank you for your contributions! As I wrote on PR #3155, we're close to submitting it.

With PR #3131, the plugin is compatible with CLion 2021.3. I already went ahead, created an out-of-turn release for the CLion 2021.3 version, and sent it to the [beta channel](https://plugins.jetbrains.com/plugin/9554-bazel/versions/beta) of the marketplace. It's currently pending approval by JetBrains but should likely show up publicly within a day. We can create a release for the stable channel next week.

**Comment by alice-ks** [comment]
PR #3155 is submitted and I created an out-of-turn release of the plugin for IntelliJ 2021.3. [This release](https://plugins.jetbrains.com/plugin/8609-bazel/versions/beta/153496) is in the [beta channel](https://plugins.jetbrains.com/plugin/8609-bazel/versions/beta) of the marketplace. Please check it out and let us know about new (runtime) incompatibilities.

See https://github.com/bazelbuild/intellij/issues/2757#issuecomment-882545832 for how to sign up to the beta channel of the public plugin repository.

We'll create a release for the stable channel next week.

**Comment by foreverlms** [comment]
Is this version incompatibility solved? The marketplace still shows incompatible and I can't use this in Clion.
![image](https://user-images.githubusercontent.com/20502148/150058044-3efeee74-13ef-42af-a3c1-831a00ed1c35.png)

**Comment by mai93** [comment]
The plugin compatible with CLion 2021.3 - 2021.3.2 is released to the beta channel. See [#2757 (comment)](https://github.com/bazelbuild/intellij/issues/2757#issuecomment-882545832) for how to sign up to the beta channel of the public plugin repository. It will be released to the stable channel soon.

**Comment by avarun42** [comment]
> We'll create a release for the stable channel next week.

Any update here?

**Comment by mai93** [comment]
The plugin is now available for IntelliJ on the stable channel.

**Comment by alice-ks** [comment]
@christi-square Thanks for the feedback. This functionality seems indeed broken. It's not something we deliberately changed for 2021.3. The run configurations which don't have Bazel in their name come from the IntelliJ platform. The Bazel plugin should suppress them and instead provide its own run configurations. That mechanism apparently doesn't work in 2021.3 anymore.

Can you please create a separate tracking issue so that we can track progress on it?

**Comment by alice-ks** [comment]
By the way, the plugin for CLion 2021.3 is also available in the stable channel since yesterday. The approval process took a bit longer this time.

**Comment by pkrishnaiahroku** [comment]
I'm on IntelliJ IDEA 2021.3.1 (Community Edition) with Bazel plugin 2022.01.25.0.0-api-version-213. 

The Bazel menu option does not show up. It appears for a few seconds when I start IntelliJ and then disappears. 

IntelliJ IDEA 2021.3.1 (Community Edition)
Build #IC-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.2

**Comment by alice-ks** [comment]
Praveen, are you sure that you opened a Bazel-based project? I remember seeing exactly the described behavior in the past for projects not being based on Bazel. When I tested the Bazel plugin's behavior in IntelliJ UE 2021.3.1 on a Bazel-based project, the menu showed up for me and I could interact with it. For your case, does the "Bazel sync" button still show up in the toolbar?

**Comment by alice-ks** [comment]
Closing this tracking bug since support for 2021.3 has been fulled rolled out. If you encounter regressions in this version, please file new reports.

**Comment by AlexeyGy** [comment]
I've also unpinned this bug and will pin 2022.1
