### ISSUE TITLE
Support for external dependencies in CLion

### ISSUE THREAD

**Issue by dionescu** [bazelbuild/intellij#38]
I know CLion plugin is not yet officially released but I was wondering whether there are any plans to support //external dependencies. For instance, it appears that the current version of the plugin cannot locate the source files for modules imported into the workspace via Bazel's new_http_archive or new_git_repo.

**Comment by brendandouglas** [comment]
We do plan to support external dependencies across all the IDEs.

Is this the same issue as #31? If so, it should be fixed in the next code drop / release (you'll also need to wait for the next Bazel build, or build from HEAD).

There are likely several further problems with external workspaces -- please let us know any you come across.

**Comment by brendandouglas** [comment]
I'll leave this open for now, just in case the fix for #31 doesn't apply.

**Comment by dionescu** [comment]
@brendandouglas: Do you know if the Bazel functionality landed in 0.4.3? Looking at the release notes I could not find anything related to C++ external dependencies.  The possibly related change for maven:

> Skylark maven_jar and maven_aar settings attribute is now a label so it can be checked into your workspace.

**Comment by brendandouglas** [comment]
@dionescu I don't see a tag or commit for 0.4.3, so not sure. The commit with the bazel-side fix was 2c2d19007818204e552f47ffe8721322a7ff8558. That's was only a few commits after 0.4.2, so it likely was in 0.4.3.

I'll update this code base soon so you can rebuild CLwB and test whether the fix is working.

**Comment by david-german-tri** [comment]
FYI, I'm finding that the plugin still does not locate the source for `WORKSPACE` externals in [RobotLocomotion/drake](https://github.com/RobotLocomotion/drake), as of https://github.com/bazelbuild/intellij/commit/879aa9f77493ceb35b72e962d3b7d218afbf087c, with Bazel 0.4.3.   I've attached a screenshot showing the symptom. 

![clwb_workspace_externals_not_indexed](https://cloud.githubusercontent.com/assets/17437069/22088241/b40dfb26-ddb0-11e6-8749-e56bea13f20e.png)

**Comment by brendandouglas** [comment]
Thanks for the repro case. This is separate from #31 (in that case, the code resolved without a problem, but 'Attach Blaze Source Jars' failed).

Fixing this will require a change to our plugin's bazel aspect, so will take some time to roll out (it will require a new bazel build).

**Comment by brendandouglas** [comment]
Actually, I misunderstood the way bazel communicates external workspace paths. There's a much simpler fix -- I'll do another code drop with the fix sometime next week.

**Comment by david-german-tri** [comment]
Awesome, thank you!  Looking forward to it.

**Comment by brendandouglas** [comment]
Should be fixed with the latest code drop -- please reopen if not.

**Comment by w4-hojin** [comment]
symbolic link to the output of 'bazel info output_base'
